#!/usr/bin/env python3
# didnt
# get rss feed from handle

import sys
import requests
from bs4 import BeautifulSoup

profile = requests.get(sys.argv[1], timeout=5)
soup = BeautifulSoup(profile.text, "html.parser")
did = soup.find(id="bsky_did")
handle = soup.find(id="bsky_handle")
print("Adding User:")
print("Handle: " + handle.text)

feed = "https://bsky.app/profile/" + did.text + "/rss"
print("Feed: " + feed)
