#!/usr/bin/env python3

"""Hurry Asteroid"""

import sys
from datetime import datetime
from pathlib import Path
import requests
from bs4 import BeautifulSoup
import feedparser
import dominate
from dominate.tags import a, footer, h1, h2, hr, link, p
from dominate.util import raw

# create data folder if needed
data_path = Path.home() / ".config" / "hurryasteroid"

if data_path.is_dir():
    pass
else:
    data_path.mkdir()
    print("data path created")

# add feed
if len(sys.argv) == 2:
    profile = requests.get(sys.argv[1], timeout=5)
    soup = BeautifulSoup(profile.text, "html.parser")
    did = soup.find(id="bsky_did")
    handle = soup.find(id="bsky_handle")
    feed = "https://bsky.app/profile/" + did.text + "/rss"
    print("Adding User:")
    print("Handle: " + handle.text)
    print("Feed: " + feed)
    with open(data_path / "users.txt", "a", encoding="utf-8") as users:
        users.write(handle.text + " " + feed + "\n")
    sys.exit()


PREVIOUS = ""

# build doc head
current_date = datetime.now().strftime("%A %d %B %Y")
doc = dominate.document(title="Hurry Asteroid")
with doc.head:
    raw('<meta charset="UTF-8">')
    raw('<meta name="viewport" content="width=device-width, initial-scale=1.0" />')
    link(rel="stylesheet", href="style.css")
    doc += h1("Hurry Asteroid")
    doc += p(current_date)

with open(data_path / "users.txt", encoding="utf-8") as file:
    for line in file:
        short_line = line.split(" ")
        d = feedparser.parse(short_line[1].strip())
        rss_title = d.feed.title.split(".")
        file_title = rss_title[0].strip("@ ")
        skeet_pub = d.entries[0].published.strip("0+ ")
        skeet_link = d.entries[0].link
        # bail early
        if not 'summary' in d.entries[0]:
            print(file_title + "no summary")
        else:
            # check if seen
            data_file = data_path / file_title
            if Path(data_file).is_file():
                with open(Path(data_file), "r", encoding="utf-8") as dataRead:
                    PREVIOUS = dataRead.read()
            if d.entries[0].link == PREVIOUS:
                print(file_title + ": nothing new")
            else:
                # build out doc
                skeet_text = d.entries[0].summary
                doc += h2(rss_title[0])
                doc += p(a(skeet_pub,href=skeet_link))
                doc += p(skeet_text)
                with open(Path(data_file), "w", encoding="utf-8") as db:
                    db.write(d.entries[0].link)

# if nothing
if "h2" not in doc:
    print(h2)
    doc += h2("Nobody has posted")
    doc += p("Or the world has ended")

# footer
doc += hr()
doc += footer("Version 0.1 - ", a("Github",href="https://github.com/phantomdiorama/hurryasteroid"))

# debug output
print(doc)

# create file
with open("hurryasteroid.html", "w", encoding="utf-8") as outputFile:
    outputFile.write(doc.render())
