#!/usr/bin/env python3

"""Hurry Asteroid"""

from pathlib import Path
import feedparser
import dominate
from dominate.tags import *
from dominate.util import raw

# build doc head
doc = dominate.document(title="The End of the World")
with doc.head:
    raw('<meta charset="UTF-8">')
    raw('<meta name="viewport" content="width=device-width, initial-scale=1.0" />')
    link(rel="stylesheet", href="style.css")
    doc += h1("The End of the World")

with open(Path("users.txt"), encoding="utf-8") as file:
    for line in file:
        d = feedparser.parse(line.strip())
        sTitle = d.feed.title.split(" ")
        fTitle = sTitle[0].strip("@ ")
        sTime = d.entries[0].published.strip("0+ ")
        sLink = d.entries[0].link
        if not 'summary' in d.entries[0]:
            print(fTitle + "no summary")
        else:
            sPost = d.entries[0].summary

            if Path(fTitle).is_file():
                with open(Path(fTitle), "r", encoding="utf-8") as dataRead:
                    before = dataRead.read()
                if d.entries[0].link == before:
                    print(fTitle + ": nothing new")
            else:
                # build out doc
                doc += h2(sTitle[0])
                doc += p(a(sTime,href=sLink))
                doc += p(sPost)
                with open(Path(fTitle), "w", encoding="utf-8") as data:
                    data.write(d.entries[0].link)


# debug output
print(doc)

# # create file
with open("hurryasteroid.html", "w", encoding="utf-8") as outputFile:
    outputFile.write(doc.render())
